### ISSUE TITLE
GeneMark.hmm 400-day license

### ISSUE THREAD

**Issue by cmajones** [lpenguin/phigaro#5]
Hi there, 

I installed phigaro as directed and after running my first command got this error: 

`phigaro -f ../virfinder/scaffolds.fasta -o phigaro_out -t 20
Traceback (most recent call last):
  File "/usr/local/bin/phigaro", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/phigaro/cli/batch.py", line 118, in main
    task_output_file = run_tasks_chain(tasks)
  File "/usr/local/lib/python2.7/dist-packages/phigaro/batch/runner.py", line 18, in run_tasks_chain
    task.run()
  File "/usr/local/lib/python2.7/dist-packages/phigaro/batch/task/gene_mark.py", line 29, in run
    self.gene_mark(self.input)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 774, in __init__
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/casey/local/MetaGeneMark_linux_64/mgm/gmhmmp -A proc/gene_mark/scaffolds-7e52b7413bc44ee6b22a6a38e45cea72.faa -m /home/casey/local/MetaGeneMark_linux_64/mgm/MetaGeneMark_v1.mod ../virfinder/scaffolds.fasta

  STDOUT:

  STDERR:
GeneMark.hmm 400-day license.
Your 400-day license period has ended. We hope that you found this
software useful. If you would like to renew this license,
please contact GeneProbe, Inc. at custserv@genepro.com`

Let me know if this is an installation issue or if I need to obtain a copy of GeneMark.hmm. 

Thanks!

**Comment by bobeobibo** [comment]
Hi. Did you download MetaGeneMark from
http://topaz.gatech.edu/Genemark/license_download.cgi ? If so, you
shouldn't receive this message, normally.
However, we are planning an update that will avoid using MetaGeneMark and
therefore their license issues.

**Comment by cmajones** [comment]
Hi there, yes I used that link and installed as indicated in the mgm download.

**Comment by ACPortmann** [comment]
Hi @bobeobibo,

According to your last year post, you were planning an update to avoid using MetaGeneMark:
> Hi. Did you download MetaGeneMark from http://topaz.gatech.edu/Genemark/license_download.cgi ? If so, you shouldn't receive this message, normally. However, we are planning an update that will avoid using MetaGeneMark and therefore their license issues.

When do you plan to release this update of phigaro?

Many thanks in advance for your answer.

**Comment by bobeobibo** [comment]
Hi @ACPortmann  ,
The updated version of Phigaro can be found here https://github.com/bobeobibo/phigaro 
We don't use mgm anymore.

Thanks for your interest in Phigaro :)
